<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="css/style.css">
  <title>Détails du film</title>
</head>

<body onload="getMovie('<?= $id ?>', getCookie('lang')); getLang(getCookie('lang'));">
  <nav class="navbar">
    <ul class="menu">
      <li class="item">
        <select name="lang" id="lang" onchange="changeLangDetail('<?= $id ?>', this);"></select>
      </li>
      <li class="item">Connexion</li>
    </ul>
  </nav>
  <div id="container">
    <a href="index.php">Back</a>
    <div id="details"></div>
    <script src="js/main.js"></script>
</body>

</html>